// Family-friendly "Would you rather" prompts. Each pair is rendered as
// "Would you rather [A] or [B]?" — kept light, silly, and safe for all
// ages: no violence, no scary/dark themes, nothing political or crude.
export const WOULD_YOU_RATHER_QUESTIONS: [string, string][] = [
  ["always eat pizza cold", "always eat ice cream melted"],
  ["never eat cheese again", "never eat chocolate again"],
  ["only eat sweet food for a month", "only eat salty food for a month"],
  ["have unlimited pancakes for breakfast forever", "unlimited tacos for dinner forever"],
  ["never drink soda again", "never eat dessert again"],
  ["always eat with chopsticks", "always eat with your hands"],
  ["have a lifetime supply of your favorite snack", "a chef who cooks you anything once a week"],
  ["only drink from a tiny teacup", "only drink through a giant curly straw"],
  ["be able to fly", "be able to turn invisible"],
  ["be able to read minds", "be able to see the future"],
  ["talk to animals", "speak every human language"],
  ["teleport anywhere instantly", "be able to freeze time"],
  ["be super strong", "be super fast"],
  ["shrink to the size of a mouse", "grow to the size of a giant"],
  ["have wings", "have a tail"],
  ["control fire", "control water"],
  ["never need sleep again", "never feel hungry again"],
  ["have a pet dragon", "have a pet unicorn"],
  ["breathe underwater", "see perfectly in the dark"],
  ["have a magic carpet", "have a jetpack"],
  ["have three wishes granted right now", "one wish that always comes true"],
  ["always have to sing instead of talk", "always have to dance everywhere you walk"],
  ["live without music", "live without movies"],
  ["wear pajamas everywhere for a week", "wear a costume everywhere for a week"],
  ["always be ten minutes late", "always be an hour early"],
  ["always have itchy socks", "always have a pebble in your shoe"],
  ["never use a phone again", "never use a computer again"],
  ["only text in emojis", "only text in ALL CAPS"],
  ["live in a treehouse", "live in a houseboat"],
  ["have super long hair", "have no hair at all"],
  ["always have messy handwriting", "always type with one finger"],
  ["never watch TV again", "never play video games again"],
  ["explore outer space", "explore the deep ocean"],
  ["live on a tropical island", "live in snowy mountains"],
  ["go camping in a tent", "go glamping at a fancy resort"],
  ["travel back in time 100 years", "travel forward in time 100 years"],
  ["visit every country on Earth", "visit every planet in the solar system"],
  ["ride in a hot air balloon", "ride in a submarine"],
  ["hike to the top of a mountain", "sail across an ocean"],
  ["be a cat for a day", "be a dog for a day"],
  ["have a pet elephant", "have a pet giraffe"],
  ["be able to talk to your pet", "have your pet understand everything you say"],
  ["ride a horse", "ride a camel"],
  ["live with 100 cats", "live with 100 dogs"],
  ["snort every time you laugh", "hiccup every time you're excited"],
  ["wear mismatched socks forever", "wear your shirt inside out forever"],
  ["only be able to whisper", "only be able to shout"],
  ["have hair that changes color with your mood", "have eyes that glow in the dark"],
  ["be double-jointed", "be able to wiggle your ears"],
  ["sneeze glitter", "sneeze confetti"],
  ["have a horn that honks when you're happy", "a bell that rings when you're surprised"],
  ["never use social media again", "never watch another video online"],
  ["have a robot best friend", "have a talking pet"],
  ["live without the internet for a month", "live without your phone for a month"],
  ["do only math homework for a year", "do only writing homework for a year"],
  ["have recess twice a day", "have lunch twice a day"],
  ["pick your own class schedule", "pick your own lunch menu every day"],
  ["be able to pause time", "be able to rewind time"],
  ["win a trip to a theme park", "win a trip to a water park"],
  ["build a giant sandcastle", "build a giant snowman"],
  ["have a treehouse with a slide", "have a treehouse with a zipline"],
  ["own a candy store", "own a toy store"],
  ["be a famous singer", "be a famous athlete"],
  ["be really good at drawing", "be really good at singing"],
  ["never lose a game again", "never lose your keys again"],
  ["have a personal chef", "have a personal chauffeur"],
  ["live in a candy house", "live in a cloud house"],
  ["always win at rock paper scissors", "always win at board games"],
  ["breathe fire safely, like a dragon", "shoot rainbows from your fingertips"],
  ["have glow-in-the-dark skin", "have rainbow-colored hair"],
  ["wake up as a superhero", "wake up as a wizard"],
  ["live in a world with no rain", "live in a world with no wind"],
  ["always smell like fresh cookies", "always smell like flowers"],
  ["have a moat around your house", "have a drawbridge to your room"],
  ["own a hoverboard", "own a go-kart"],
  ["be able to talk to plants", "be able to talk to the weather"],
  ["never do chores again", "never do homework again"],
  ["have a room that changes color with a snap", "have a room that plays your favorite song when you enter"],
  ["always find money on the ground", "always find your favorite snack in your bag"],
  ["have a pool in your backyard", "have a trampoline in your backyard"],
  ["be the best at video games", "be the best at sports"],
  ["have a talking parrot", "have a talking cat"],
  ["wear a cape every day", "wear a crown every day"],
  ["live in a lighthouse", "live in a windmill"],
  ["have unlimited popcorn at every movie", "have unlimited candy at every movie"],
  ["skip winter every year", "skip summer every year"],
  ["have a garden that grows candy", "have a garden that grows toys"],
  ["always get the window seat", "always get to pick the music on car rides"],
  ["have a pet that can fly", "have a pet that can talk"],
  ["build blanket forts all day", "build sandcastles all day"],
  ["have super soft hands", "have super strong hands"],
  ["be able to jump really high", "be able to run really fast"],
  ["have a backyard water slide", "have a backyard zipline"],
];
